### ISSUE TITLE
Questions regarding GDT

### ISSUE THREAD

**Issue by Simolation** [Lixfeld/VSCode-GDT-Extension#1]
Hey!
I have seen your GDT VS Code extension, and it is really helpful. 
I think you know quite a lot about GDT, and I still have some problems integrating GDT.

So, I wanted to ask if you could help me and answer some questions on a call? Feel free to email me at hi@simolation.de.

**Comment by Lixfeld** [comment]
Thanks for the feedback.
Documentations for GDT can be found here: https://www.qms-standards.de/standards-zum-download/
(Closing because no real issue with the extension)
